trungvu256/du_an_tot_nghiep

app/Http/Controllers/Admin/UserController.php, app/Models/User.php, resources/views/admin/layouts/header.blade.php, resources/views/admin/user/add.blade.php
=> code_userAdmin

app/Http/Controllers/Admin/CommentController.php, database/migrations/2021_11_12_142607_create_comments_table.php, resources/views/admin/comment/add.blade.php, resources/views/admin/layouts/side-bar.blade.php, routes/web.php
=> add_comment

resources/views/admin/blog/edit.blade.php
=> thay doi link js

app/Http/Controllers/Admin/UserController.php, app/Models/User.php, database/migrations/2014_10_12_000000_create_users_table.php, resources/views/admin/user/edit.blade.php, resources/views/admin/user/index.blade.php, routes/web.php
=> user_login_regiter

app/Http/Controllers/Web/ProfileController.php, resources/views/web2/confirm_password.blade.php, resources/views/web2/layout/header.blade.php, resources/views/web2/profile.blade.php, resources/views/web2/profile_edit.blade.php, routes/web.php
=> thêm_xem_chỉnh_sửa_thông_tin

app/Http/Controllers/Admin/OrderController.php, app/Models/Order.php, app/Models/OrderDetail.php, resources/views/admin/layouts/side-bar.blade.php, resources/views/admin/order/detailOder.blade.php, resources/views/admin/order/index.blade.php, resources/views/admin/product/show.blade.php, resources/views/web2/Home/home.blade.php
=> code_order

app/Http/Controllers/Admin/OrderController.php, app/Models/Order.php, app/Models/Product.php, database/migrations/2021_11_04_074311_create_products_table.php, database/migrations/2021_11_10_154913_create_orders_table.php, database/migrations/2021_11_11_144500_add_column_status_to_table_orders.php, database/migrations/2025_03_11_134414_add_deleted_at_to_products_table.php, resources/views/admin/order/index.blade.php, routes/web.php
code_capnhattrangthaithanhtoan
=> code_capnhattrangthaithanhtoan

app/Http/Controllers/Admin/WalletController.php, app/Models/User.php, app/Models/Wallet.php, database/migrations/2025_03_11_142240_add_payment_method_to_orders.php, database/migrations/2025_03_11_143442_create_wallets_table.php, resources/views/admin/order/index.blade.php, routes/web.php
=> Capnhat-trang_thai_hoan_tien

app/Http/Controllers/Admin/WalletController.php, app/Models/AdminWallet.php, app/Models/Wallet.php, app/Models/WalletTransaction.php, database/migrations/2021_11_10_154913_create_orders_table.php, database/migrations/2025_03_11_142240_add_payment_method_to_orders.php, database/migrations/2025_03_11_143442_create_wallets_table.php, database/migrations/2025_03_11_153134_create_admin_wallets_table.php, database/migrations/2025_03_11_163303_create_wallet_transactions_table.php, resources/views/admin/layouts/side-bar.blade.php, resources/views/admin/order/detailOder.blade.php, resources/views/admin/order/index.blade.php, resources/views/admin/wallets/show.blade.php, routes/web.php
code_thanhtoanvanaptien cua admin
=> code_thanhtoanvanaptien

app/Http/Controllers/Admin/LoginController.php, routes/web.php
=> day_lai_web

resources/views/admin/login/index.blade.php
=> day_lai_file_admin

resources/views/web2/Blogs/ListBlog.blade.php, resources/views/web2/Blogs/dettailBlog.blade.php
=> them_menuvaofBlog

resources/views/web2/layout/header.blade.php, resources/views/web2/profile.blade.php
=> sua_giao_dien_home

resources/views/admin/user/index.blade.php
=> suaquanlykhachang

app/Http/Controllers/Admin/ProductController.php, app/Http/Controllers/Web/CartController.php, resources/views/web2/Home/home.blade.php, resources/views/web2/Home/shop-detail.blade.php
=> sualai_anhoproduct

app/Http/Controllers/Admin/ProductController.php, app/Models/Attribute.php, app/Models/AttributeValue.php, app/Models/Product.php, app/Models/ProductVariant.php, resources/views/admin/product/add.blade.php
=> thembienthe

app/Http/Controllers/Web/CartController.php, app/Http/Controllers/Web/CheckoutController.php, app/Models/ProductVariantAttribute.php, app/Models/Promotion.php, resources/views/web2/Home/cart.blade.php, resources/views/web2/Home/shop-detail.blade.php, resources/views/web2/layout/header.blade.php, routes/web.php
=> capnhatgiohang

app/Http/Controllers/Web/CartController.php, app/Http/Controllers/Web/CheckoutController.php, resources/views/web2/Home/cart.blade.php, resources/views/web2/Home/checkout.blade.php, resources/views/web2/layout/header.blade.php, routes/web.php
=> lamcheckdonhang

app/Http/Controllers/Web/BlogController.php, app/Http/Controllers/Web/CheckoutController.php, app/Http/Controllers/Web/OrderController.php
=> fixcategoris

app/Http/Controllers/Admin/ProductController.php, resources/views/admin/product/edit.blade.php, resources/views/admin/product/show.blade.php
=> suashow_edit

app/Http/Controllers/Web/OrderController.php, database/migrations/2025_04_05_062009_create_return_reasons_table.php, database/seeders/ReturnReasonSeeder.php, resources/views/admin/order/index.blade.php, resources/views/web2/Home/order.blade.php, resources/views/web2/Home/orderItem.blade.php, routes/web.php
=> trangthai_giaodien

app/Http/Controllers/Web/CheckoutController.php, app/Models/Order.php, resources/views/web2/Home/orderItem.blade.php
=> sualaidathang

app/Http/Controllers/Admin/OrderController.php, app/Models/Order.php, resources/views/admin/order/detailOder.blade.php, resources/views/admin/order/index.blade.php, resources/views/web2/Home/checkout.blade.php, resources/views/web2/Home/order.blade.php
=> fixtrangthai

app/Http/Controllers/Web/CartController.php, resources/views/web2/Home/cart.blade.php, routes/web.php
=> sualaisoluonggiohang

app/Http/Controllers/Web/CheckoutController.php, routes/web.php
=> sualaikhimuahang

app/Http/Controllers/Web/WebController.php, resources/views/web2/Home/product_list.blade.php
=> fillter_product

app/Http/Controllers/Web/CartController.php, app/Http/Controllers/Web/LoginController.php, app/Http/Controllers/Web/WebController.php, resources/views/web3/Home/home.blade.php, resources/views/web3/layout/header.blade.php, resources/views/web3/layout/tab.blade.php, routes/web.php
=> dodulieuhome

app/Http/Controllers/Web/WebController.php, resources/views/web3/Home/filter_form.blade.php, resources/views/web3/Home/home.blade.php, resources/views/web3/Home/product_list.blade.php, resources/views/web3/Home/shop-detail.blade.php, resources/views/web3/Home/shop.blade.php, resources/views/web3/layout/header.blade.php, routes/web.php
=> fillter_detail_product_cate

app/Http/Controllers/Web/CartController.php, app/Http/Controllers/Web/CheckoutController.php, resources/views/web2/Home/checkout.blade.php, resources/views/web3/Home/cart.blade.php, resources/views/web3/Home/checkout.blade.php, resources/views/web3/Home/shop-detail.blade.php, resources/views/web3/layout/menu.blade.php, resources/views/web3/layout/tab.blade.php, routes/web.php
=> thieu_sanphamlienquan

app/Http/Controllers/Controller.php, app/Http/Controllers/Web/CheckoutController.php, app/Mail/OrderPlacedMail.php, config/mail.php, database/migrations/2025_04_12_160816_add_order_code_to_orders_table.php, database/migrations/2025_04_12_161150_add_return_note_to_orders_table.php, resources/views/email.blade.php, routes/web.php
=> thongbaogmail

app/Http/Controllers/Admin/LoginController.php
=> fix_login_admin

app/Http/Controllers/Web/LoginController.php, resources/views/web3/layout/tab.blade.php
=> up_regiter

resources/views/web3/layout/tab.blade.php
=> fix_icon_login

app/Http/Controllers/Admin/ProductController.php, resources/views/admin/product/add.blade.php
=> fix_bug_varians

resources/views/web3/layout/footer.blade.php
=> fix_footer

app/Http/Controllers/Web/LoginController.php, resources/views/web3/layout/tab.blade.php, routes/web.php
=> fix_loginn

resources/views/web3/layout/tab.blade.php, routes/web.php
=> fix_bug_01

resources/views/web3/Home/cart.blade.php, resources/views/web3/Home/checkout.blade.php, resources/views/web3/Home/order.blade.php, resources/views/web3/Home/orderItems.blade.php, resources/views/web3/Home/shop-detail.blade.php
=> fixcodemoi

app/Http/Controllers/Web/WebController.php, resources/views/web3/Home/shop.blade.php
Sửa phần lọc sản phẩm theo danh mục
=> edit view shop
